title: Math Towards Machine Learning
author: Huijun Zhao
email: huijunzhao.ds@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Make time for civilization, for civilization won't make time.
  ― Liu Cixin, The Dark Forest
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#show_excerpts: true # set to true to show excerpts on the homepage
github_username:  huijunzhao-ds

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - projects.md

# Build settings
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
# - jekyll-seo-tag